// Generated by scripts/sync-engine.mjs in the ColorsMine app repo.
// The engine imports these three shapes as types only; the app modules that
// declare them (the extractor and the 10.4M-palette catalog) are not part of
// the CLI and are not vendored here.

export type Role =
  | 'primary' | 'secondary' | 'accent' | 'surface' | 'text'
  | 'border' | 'error' | 'warning' | 'success'

export interface ExtractedColor {
  hex: string
  rgb: [number, number, number]
  hsl: [number, number, number]
  weight: number
  chroma?: number
  lightness?: number
}

export type RoleMap = Partial<Record<Role, ExtractedColor>>

export interface ContrastResult {
  ratio: number
  level: 'AAA' | 'AA' | 'AA Large' | 'Fail'
  adjusted?: string
}

export interface CatalogPalette {
  id: string
  name: string
  colors: string[]
  tags: string[]
  lab: [number, number, number][]
}
